site_name: Secure Tunneling Labs
site_url: https://netexperiments.github.io/SecureTunnelingLabs/
site_description: Secure Tunneling Labs is a collection of experiments and tutorials that demonstrate the use of various tunneling protocols and techniques for secure communication over untrusted networks. The labs cover a range of protocols, including MACsec, ANYsec, WireGuard, IPsec, TLS, DTLS, SSH, PKI, and PQ.
site_author: Miguel

repo_url: https://github.com/netexperiments/securetunnels
repo_name: netexperiments/securetunnels

theme:
  name: material

  language: en

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    # Navigation
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.instant

    # Search
    - search.suggest
    - search.highlight
    - search.share

    # Content
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips

    # TOC
    - toc.follow

  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  # Code highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.inlinehilite
  - pymdownx.superfences

  # Admonitions
  - admonition
  - pymdownx.details

  # Tabs
  - pymdownx.tabbed:
      alternate_style: true

  # Better lists
  - sane_lists

  # Tables
  - tables

  # Task lists
  - pymdownx.tasklist:
      custom_checkbox: true

  # Emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator:
        !!python/name:material.extensions.emoji.to_svg # Keyboard keys


  - pymdownx.keys

  # Mermaid diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # Footnotes


  - footnotes

  # Attribute lists
  - attr_list

  # Image Extensions
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/netexperiments

nav:
  - Home: index.md

  - Artifact Overview: artifact_overview/index.md

  - Emulator Setup:
      - ContainerLab: containerlab/index.md
      - GNS3: gns3/index.md

  - Experiments:
      - MACsec:
          - Overview: macsec/index.md
          - Experiments: macsec/experiments.md
      - ANYsec:
          - Overview: anysec/index.md
          - Experiments: anysec/experiments.md
      - WireGuard:
          - Overview: wireguard/index.md
          - Experiments: wireguard/experiments.md
      - IPsec:
          - Overview: ipsec/index.md
          - Experiments: ipsec/experiments.md
      - TLS:
          - Overview: tls/index.md
          - Experiments: tls/experiments.md
      - DTLS:
          - Overview: dtls/index.md
          - Experiments: dtls/experiments.md
      - SSH:
          - Overview: ssh/index.md
          - Experiments: ssh/experiments.md
      - PKI:
          - Overview: pki/index.md
          - Experiments: pki/experiments.md
      - PQ and Hybrid Mechanisms:
          - Overview: pq/index.md
          - Experiments: pq/experiments.md
